# Generated by Django 5.0.2 on 2024-12-25 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deployedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='Projects/')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Py', 'PYTHON'), ('J', 'JAVA'), ('ML', 'Machine Learning'), ('Js', 'Javascript')], max_length=2)),
            ],
        ),
    ]
